### ISSUE TITLE
[1.0.3] Quest Reward "More Tools" missing material on shovel head reward

### ISSUE THREAD

**Issue by Targren** [Filostorm/Multiblock-Madness#32] opened 2021-04-26 18:55 UTC
Shovel head reward for this quest in  the first chapter says "Missing Material: certusquartz_plustic" and has a durability of 1.

**Comment by Filostorm** [comment] 2021-04-26 19:16
This is caused by the temporary addition of Tinkers Evolution overwriting some material types. 

The mod was voted out, and so will be removed in the next update. 

Thanks for the report!

**Comment by Filostorm** [comment] 2021-05-01 23:27
Fixed in 1.0.4

**Closed by Filostorm** 2021-05-01 23:27 UTC
